server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
            - name: JwtAuthenticationFilter

        - id: music-service
          uri: ${MUSIC_SERVICE_URL}
          predicates:
            - Path=/music/**
          filters:
            - RewritePath=/music/(?<segment>.*), /${segment}
            - name: JwtAuthenticationFilter