spring.application.name=music-service
server.port=8082

# Conexiunea la baza de date intern? Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Set?ri JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google Drive Config (Folosim variabil? pentru folder ID ca s? o po?i schimba din dashboard)
google.drive.folder.id=${GOOGLE_DRIVE_FOLDER_ID}

# JWT Secret (Trebuie s? fie acela?i ca la Auth pentru a valida token-urile)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970